
create database online_shopping;

-- 1. List all unique cities where customers are located.

select distinct(customer_city)
from customers;

-- 2. Count the number of orders placed in 2017

select count(*) as total_order
from  orders
where year(order_approved_at) = 2017;

 -- 3. Find the total sales per category. 

 select *
 from products;

 select *
 from order_items;

 select y.product_category,round(sum(x.price ),2)  as total 
 from order_items x
 inner join products y on x.product_id = y.product_id
 group by y.product_category
 order by total desc;

 -- 4. Calculate the percentage of orders that were paid in installments.

 select *
 from payments;

 select * from orders;

select 
  (count(case when payment_installments >1 then 1 end) *100)/
  count(*) as installment_percentage
  from payments;

  -- 5. Count the number of customers from each state.

select customer_state, count(*) as total_customer
from customers
group by customer_state;

-- 1. Calculate the number of orders per month in 2018

select month(order_purchase_timestamp) as order_month ,count(*) as total_order
from orders
where year(order_purchase_timestamp)   = 2018
group by month(order_purchase_timestamp)
order by order_month asc;


-- 2. Find the average number of products per order, grouped by customer city. 

select c.customer_city,count(a.product_id)* 1.0/count(distinct o.order_id) as averag_product_per_order
from orders o
join customers c on o.customer_id = c.customer_id
join order_items a on o.order_id = a.order_id
group by c.customer_city;


-- 3. Calculate the percentage of total revenue contributed by each product category. 


select x.product_category,round(sum(y.price+y.freight_value),2) as revenue,round(sum(y.price),3) * 100.0/sum(sum(y.price)) over() as reveune_percentage
from order_items y
join products x on y.product_id = x.product_id
group by x.product_category;




-- 4. Calculate the total revenue generated by each seller, and rank them by revenue.

select * from sellers;

select * from order_items;

select x.seller_id, round(sum(y.price+ y.freight_value),2) as total_revenue , rank() over(order by sum(y.price+ y.freight_value) desc) as seller_rank
from sellers x
join order_items y on x.seller_id = y.seller_id
group by x.seller_id;


-- 1. Calculate the moving average of order values for each customer over their order history.

select a.customer_id, a.order_id ,a.order_purchase_timestamp,
       round(sum(b.price + b.freight_value),2) as order_value,
       avg(sum(b.price + b.freight_value)) 
       over(partition by a.customer_id 
       order by a.order_purchase_timestamp
       rows between unbounded preceding and current row) as moving_avg
from orders a
join order_items b on a.order_id = b.order_id
group by a.customer_id , a.order_id , a.order_purchase_timestamp
order by a.customer_id , a.order_purchase_timestamp;



-- 2. Calculate the cumulative sales per month for each year

select * from orders;
select * from order_items;

select year(x.order_purchase_timestamp) as order_year,
       month(x.order_purchase_timestamp) as order_month,
       sum(y.price + y.freight_value) as monthly_sales,
       sum(sum(y.price + y.freight_value)) over(partition by year(x.order_purchase_timestamp)
       order by month(x.order_purchase_timestamp)) as cumulative_sales

from orders x
join order_items y on x.order_id = y.order_id
group by year(x.order_purchase_timestamp),
         month(x.order_purchase_timestamp)
order by 
       order_year, order_month;


/*select sum(price) over()
from order_items;*/

 -- 3. Calculate the year-over-year growth rate of total sales

 select year(y.order_purchase_timestamp),round(sum(x.price),2) as year_total
 from orders y
 join order_items x on y.order_id = x.order_id
 group by year(y.order_purchase_timestamp);




-- 4. Identify the top 3 customers who spent the most money in each year.

select * from order_items;
select * from orders;

select top 3 * from (select a.customer_id,year(a.order_purchase_timestamp) as order_year,
               sum(b.price + b.freight_value) as order_spent,
               rank() over(partition by year(a.order_purchase_timestamp)
               order by sum(b.price +b.freight_value) desc) as rnk
from orders a
join order_items b on a.order_id = b.order_id 
group by a.customer_id , year(a.order_purchase_timestamp)) t
where rnk <= 3
order by order_year , rnk;





 




