
create database online_shopping;

-- 1. List all unique cities where customers are located.

select distinct(customer_city) as unique_1
from customers
order by unique_1 asc;

-- 2. Count the number of orders placed in 2017

select count(order_purchase_timestamp) as total_order
from  orders
where year(order_purchase_timestamp) = 2017
and order_purchase_timestamp IS NOT NULL;

 -- 3. Find the total sales per category. 

 select *
 from products;

 select *
 from order_items;

 select y.product_category,round(sum(x.price ),2)  as total 
 from order_items x
 inner join products y on x.product_id = y.product_id
 group by y.product_category
 order by total desc;

 -- 4. Calculate the percentage of orders that were paid in installments.

 select *
 from payments;

 SELECT COUNT(*) FROM payments;

SELECT COUNT(*) 
FROM payments 
WHERE payment_installments > 1;

select 
  (count(case when payment_installments >1 then 1 end) *100)/
  count(*) as installment_percentage
  from payments
  WHERE payment_installments IS NOT NULL;

  -- 5. Count the number of customers from each state.

select customer_state, count(*) as total_customer
from customers
group by customer_state
order by total_customer desc;

-- 1. Calculate the number of orders per month in 2018

select month(order_purchase_timestamp) as order_month ,count(*) as total_order
from orders
where year(order_purchase_timestamp)   = 2018
group by month(order_purchase_timestamp)
order by order_month asc;


-- 2. Find the average number of products per order, grouped by customer city. 


SELECT c.customer_city,CAST(COUNT(a.product_id)*1.0 
        / COUNT(DISTINCT o.order_id)AS DECIMAL(10,1)
    ) AS average_products_per_order
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items a ON o.order_id = a.order_id
GROUP BY c.customer_city
ORDER BY average_products_per_order DESC;


-- 3. Calculate the percentage of total revenue contributed by each product category. 


select x.product_category,round(sum(y.price+y.freight_value),0) as 
revenue,cast(sum(y.price) * 100.0/sum(sum(y.price))  
over() as decimal(10,1)) as reveune_percentage
from order_items y
join products x on y.product_id = x.product_id
group by x.product_category
order by reveune_percentage desc;


-- 4. Calculate the total revenue generated by each seller, and rank them by revenue.

select * from sellers;

select * from order_items;

select x.seller_id, round(sum(y.price+ y.freight_value),2) as total_revenue ,
rank() over(order by sum(y.price+ y.freight_value) desc) as seller_rank
from sellers x
join order_items y on x.seller_id = y.seller_id
group by x.seller_id
order by seller_rank asc;

--5. . Identify the correlation between product price and the number of times a product has been purchased.

WITH product_data AS (SELECT product_id,
CAST(COUNT(order_id) AS FLOAT) AS time_purchased,
CAST(AVG(price) AS FLOAT) AS price
FROM order_items
GROUP BY product_id)
SELECT(AVG(price * time_purchased) - AVG(price) * AVG(time_purchased))
 /NULLIF(STDEV(price) * STDEV(time_purchased), 0) AS correlation
FROM product_data
WHERE price IS NOT NULL 
AND time_purchased IS NOT NULL;
 





-- 1. Calculate the moving average of order values for each customer over their order history.

select a.customer_id, a.order_id ,a.order_purchase_timestamp,
       round(sum(b.price + b.freight_value),2) as order_value,
       cast(avg(sum(b.price + b.freight_value)) 
       over(partition by a.customer_id 
       order by a.order_purchase_timestamp
       rows between unbounded preceding and current row) as decimal(10,2)) as moving_avg
from orders a
join order_items b on a.order_id = b.order_id
group by a.customer_id , a.order_id , a.order_purchase_timestamp;




-- 2. Calculate the cumulative sales per month for each year

select * from orders;
select * from order_items;

select year(x.order_purchase_timestamp) as order_year,
       month(x.order_purchase_timestamp) as order_month,
       round(sum(y.price + y.freight_value),2) as monthly_sales,
       round(sum(sum(y.price + y.freight_value)) 
       over(partition by year(x.order_purchase_timestamp)
       order by month(x.order_purchase_timestamp)),2) as cumulative_sales
from orders x
join order_items y on x.order_id = y.order_id
group by year(x.order_purchase_timestamp),
         month(x.order_purchase_timestamp)
order by order_year, order_month;


/*select sum(price) over()
from order_items;*/

 -- 3. Calculate the year-over-year growth rate of total sales



 WITH yearly_sales AS (SELECT 
    YEAR(y.order_purchase_timestamp) AS year,
    ROUND(SUM(x.price),2) AS year_total
    FROM orders y
    JOIN order_items x ON y.order_id = x.order_id
    GROUP BY YEAR(y.order_purchase_timestamp))
SELECT year,year_total,
    LAG(year_total) OVER (ORDER BY year) AS previous_year_sales,
    ROUND(((year_total - LAG(year_total) OVER (ORDER BY year))
        / LAG(year_total) OVER (ORDER BY year)) * 100,2) AS yoy_growth_rate
FROM yearly_sales;




-- 4. Identify the top 3 customers who spent the most money in each year.

select * from payments;
select * from orders;

select * from (select a.customer_id,year(a.order_purchase_timestamp) as order_year,
               round(sum(payment_value),2) as order_spent,
               rank() over(partition by year(a.order_purchase_timestamp)
               order by sum(payment_value) desc) as rnk
from orders a
join payments b on a.order_id = b.order_id 
group by a.customer_id , year(a.order_purchase_timestamp)) t
where rnk <= 3
order by order_year , rnk;

--5. Calculate the retention rate of customers, defined as the percentage of customers 
--who make another purchase within 6 months of their first purchase. 

WITH first_purchase AS (SELECT customer_id,
MIN(order_purchase_timestamp) AS first_purchase_date
FROM orders
GROUP BY customer_id),
merged AS (SELECT 
o.customer_id,
o.order_purchase_timestamp,
fp.first_purchase_date,
DATEDIFF(DAY, fp.first_purchase_date, o.order_purchase_timestamp) AS date_diff
FROM orders o
JOIN first_purchase fp 
ON o.customer_id = fp.customer_id),
repeat_customers AS (SELECT DISTINCT customer_id
FROM merged
WHERE date_diff > 0 
AND date_diff <= 180)
SELECT COUNT(*) * 100.0 / 
(SELECT COUNT(*) FROM first_purchase) AS retained_rate
FROM repeat_customers;





 




